### PR TITLE
implement `shuf`

### PR DESCRIPTION
**Pull request by Taillook**
implement `shuf` #58

### CODE REVIEW

**Comment by JalonSolov** [comment]
Looks pretty good.  Only 2 suggestions:
* Don't forget the count at the top of the `Completed` table.
* Please use the `common` module for command line flags.  It will keep everything consistent.

**Comment by Taillook** [comment]
@JalonSolov 
`Completed` Incremented, and use common module.

**Comment by Taillook** [comment]
I thought this github actions error is not my work.(wc, uname, printf

**Comment by JalonSolov** [comment]
Thanks for the changes!  You are correct, those failures are due to recent changes in V - have to get those fixed.

**Comment by Taillook** [comment]
Thanks for the quick review!

**Comment by JalonSolov** [comment]
The other things are fixed as well.

**Pull request merged**
