### PR TITLE
Implement tac cmd.

### PR DESCRIPTION
**Pull request by andreas-hofmann**

### CODE REVIEW

**Comment by JalonSolov** [comment]
Thanks for the PR!

I do have a few suggestions, to make the code more closely match the other tools in this repo.

When adding a new tool, don't forget to increment the number completed in the README.

Your code can also be made shorter by taking further advantage of the `common` module.  For example, `-h,--help` and `--version` are already handled, and will output those things in a style that matches the rest of the utils.

You should call `fp.finalize()` to make certain everything is closed properly.  It will return any remaining arguments, which should be the filenames entered on the command line.

It looks like you try to read from stdin if no files were given, which is good, but the user could also enter and actual `-` on the command line (which also means read from stdin).  That will have to be handled the same as if no filenames were given at all.

**Comment by andreas-hofmann** [comment]
Thanks for your feedback, highly appreciated! Just dipping my toes into V, so please bear with me. I've taken care of the issues you mentioned, but actually the regex-setting is currently still without effect. Please feel free to hold back the merge until I've added this functionality, too.

**Comment by JalonSolov** [comment]
Alright, I'll hold until you say it's ready.  In the meantime, I'll approve so the CI runs, in case that find something.

**Comment by JalonSolov** [comment]
So it did find one thing... need to run `v fmt -w tac.v` :-)

**Comment by JalonSolov** [comment]
Any progress?

**Comment by dumblob** [comment]
This is the first utility I checked, so I might be wrong. But shouldn't we actually make these streaming utilities actually stream the data?

Reading them whole into memory is IMHO the worst solution in the times of major I/O gains by io_uring in Linux and similar APIs on other OSes.

**Comment by JalonSolov** [comment]
The guiding principle should always be "Make it work, first, _then_ optimize."

**Comment by syrmel** [comment]
Any objections to closing this (superseded by PR #128)?

**Pull request closed without merging**
