### PR TITLE
fix: do not print `-` when reading from stdin (#53)

### PR DESCRIPTION
**Pull request by dundee**

### CODE REVIEW

**Comment by JalonSolov** [comment]
There is also leading whitespace before the count:
```
jamie@5950x coreutils]$ wc -l README.md // GNU version
144 README.md
[jamie@5950x coreutils]$ bin/wc -l README.md // V coreutils version
  144 README.md
[jamie@5950x coreutils]$
```

**Comment by dundee** [comment]
> There is also leading whitespace before the count:
> 
> ```
> jamie@5950x coreutils]$ wc -l README.md // GNU version
> 144 README.md
> [jamie@5950x coreutils]$ bin/wc -l README.md // V coreutils version
>   144 README.md
> [jamie@5950x coreutils]$
> ```

I am not sure if we should copy the behaviour of wc exactly as it is. There is leading whitespace in some cases and isn't in other:

```shell
$ wc -l README.md 
144 README.md
$ wc README.md 
 144 1261 9272 README.md
 ```

**Comment by JalonSolov** [comment]
We want it as close as it is possible to make it, just in case it will make the difference between other code working or not.  That's the main issue with trying to duplicate the functionality of something that already exists... it has to be as exact a duplicate as possible, or people won't want to use it.

There are definite differences in the `--help` output, but those can only be fixed by modifying V's `flag` module, or writing a completely separate common parser.

**Comment by dundee** [comment]
Ok, I will give it a try.

**Comment by JalonSolov** [comment]
Thanks!

**Pull request merged**
