### PR TITLE
implement mkdir command

### PR DESCRIPTION
**Pull request by zhihau**

### CODE REVIEW

**Comment by JalonSolov** [comment]
We cannot accept this PR as-is.  Please reformat and change all the CRLF line endings to LF only.  Then you should only have changes in the `mkdir` files, instead of every single file.

**Comment by JalonSolov** [comment]
Better yet, pull the latest code - I have changed the `.gitattributes` file to force all files to `eol=lf`.

**Comment by spytheman** [comment]
I've just rebased over current master, and ran vfmt. The new command still misses tests for now though.

**Comment by JalonSolov** [comment]
With no further responses from the author, closing in favor of #96

**Pull request closed without merging**
