### PR TITLE
Adding the uniq utility

### PR DESCRIPTION
**Pull request by syrmel**
Attached a V-based version of the coreutil `uniq` according to POSIX spec (https://pubs.opengroup.org/onlinepubs/9699919799/utilities/uniq.html) and implementing the same options as in GNU coreutils 9.3.

I could not find a better way to add a read_line_until() method to the BufferedReader; happy for advice on this.

Future work: improve tests to include more complex cases, ideally with a test case generator (a few with large files have been done manually ad hoc, though).

Thanks for V and this project!

### CODE REVIEW

**Comment by JalonSolov** [comment]
BufferedReader.read_line is documented as doing what your custom version does...
```
read_line attempts to read a line from the buffered reader it will read until it finds a new line character (\n) or the end of stream.
```

**Comment by syrmel** [comment]
I just realized I did not update the documentation on read_line_until(). Instead of the standard BufferedReader.read_line, I was going for this:
`pub fn (mut r BufferedReader) read_line_until(line_delim u8) !string` 
to be able to work consistently with lines terminated by other characters than \n, such as \0 for running utils with the zero-terminated option.

**Comment by JalonSolov** [comment]
Gotcha.  Ok, then... perhaps a PR to V to add a `delimiter` parameter?  It should be optional, with a default of `\n`.

This seems like a useful addition to the main routine, and would prevent having to duplicate so much out of vlib.

**Comment by syrmel** [comment]
Thanks! I will go ahead and do that and, if accepted, update this.

I was trying to find a way to just enhance the vlib BufferedReader functionality with an embedded struct but couldn't figure out how to make that work (because I could not use the private methods of the original).

**Comment by JalonSolov** [comment]
That can definitely get interesting... but not needed if you get a change in vlib directly.  :-)

**Comment by syrmel** [comment]
The change is in vlib and this code has been cleaned up accordingly.

**Comment by JalonSolov** [comment]
The CI failures are unrelated to this PR.

**Pull request merged**
