### PR TITLE
implement `uptime`

### PR DESCRIPTION
**Pull request by ShenTengTu**
-  #43 
- #44 

The basic features are completed, but there are some issues need to solve:
- Declare sub struct correctly in `C.utmpx`
  - https://github.com/bminor/glibc/blob/master/sysdeps/gnu/bits/utmpx.h#L55 
- Resolve conflicts with `C.timeval` in `<time.h>`
  - `C.timeval` in `<utmpx.h>` is from `<bits/types/struct_timeval.h>`
- Compilation error occurs when printing `C.utmpx` object.
  - `cannot convert 'struct <anonymous>' to 'struct timeval'`
- Resolve different user counts when running `uptime /var/log/wtmp`

### CODE REVIEW

**Comment by JalonSolov** [comment]
Files with C calls in them should be in `.c.v` files.  Only pure V code should be in plain `.v` files.

This will become an error in the future.

Plain `.v` files are assumed to be code that is portable to all systems, and all backends (including JavaScript, native x64, etc.).

**Comment by ShenTengTu** [comment]
The local test of `uptime` has passed, using GNU coreutils built from source code.

**Comment by JalonSolov** [comment]
One of your tests is failing.  `uptime_test.v` - `fn test_print_uptime`

A assert is failing.

**Comment by ShenTengTu** [comment]
> One of your tests is failing.  `uptime_test.v` - `fn test_print_uptime`
> 
> A assert is failing.

The problem has been mentioned in Discord. CI environment must use GNU coreutils built from source code, because some commands in Ubuntu are from `procps`.

**Comment by JalonSolov** [comment]
Closing/re-opening to force CI to run again.

**Comment by JalonSolov** [comment]
The `expr` test failure is being looked into.  It appears there is also an `uptime` test failure.

**Comment by JalonSolov** [comment]
The uptime failure is due to the output being different in the amount of time the system has been up.
```
[jamie@5950x coreutils]$ bin/uptime && uptime
 22:00:20  up  0:14,  6 users,  load average: 0.38, 0.36, 0.24
 22:00:20 up 14 min,  6 users,  load average: 0.38, 0.36, 0.24
[jamie@5950x coreutils]$
```
Note that the V version printed `0:14` while the GNU version printed `14 min`.

The V version also has the extra space between current time and the word `up`.

**Comment by ShenTengTu** [comment]
> The uptime failure is due to the output being different in the amount of time the system has been up.
> 
> ```
> [jamie@5950x coreutils]$ bin/uptime && uptime
>  22:00:20  up  0:14,  6 users,  load average: 0.38, 0.36, 0.24
>  22:00:20 up 14 min,  6 users,  load average: 0.38, 0.36, 0.24
> [jamie@5950x coreutils]$
> ```
> 
> Note that the V version printed `0:14` while the GNU version printed `14 min`.
> 
> The V version also has the extra space between current time and the word `up`.

GNU version doesn't print time unit, it is feature of `procps` version.

Command:
```
$ uptime --version;echo "";uptime;v run src/uptime
```
Output:
```
uptime (GNU coreutils) 8.32.169-d6125
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Joseph Arceneaux, David MacKenzie, and Kaveh Ghazi.

 13:32:34  up   0:26,  1 user,  load average: 0.44, 0.63, 0.70
 13:32:35  up  0:26,  1 user,  load average: 0.44, 0.63, 0.70
```

There is just some space align problem with V version.

**Pull request merged**
