### PR TITLE
doc: better formatting

### PR DESCRIPTION
**Pull request by Hunam6**
As checkboxes are not rendered in tables, I propose another formatting.

### CODE REVIEW

**Comment by JalonSolov** [comment]
What is the point of changing the checkbox to an `X` or `V`?

You also changed the name of the tool from `ptx` to `pt X` which was likely a search/replace problem, but still is a problem in the final output since `ptx` is the name of the command.

**Comment by Hunam6** [comment]
@JalonSolov Thanks, issue fixed.
> What is the point of changing the checkbox to an X or V?

As I said, the [checkbox GH Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) that is currently used in the [table GH Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), doesn't render inside the tables, so I propose another formatting that I believe is clearer.

**Comment by JalonSolov** [comment]
I tried several different methods to get an actual checkmark, and finally found one that works using an HTML entity.

If you have ideas for making it looks better now, please update this PR (after syncing with the current changes).

**Comment by Hunam6** [comment]
Excellent idea @JalonSolov!

**Pull request closed without merging**
