### PR TITLE
add nohup and make echo use common parser

### PR DESCRIPTION
**Pull request by stonesword0**

### CODE REVIEW

**Comment by JalonSolov** [comment]
Need to run `v fmt -w` on your changed files.

**Comment by stonesword0** [comment]
Ran v fmt

**Comment by stonesword0** [comment]
Huh. Thats weird, on my end it says the files are already formatted

**Comment by JalonSolov** [comment]
I just pulled your PR and checked with `v fmt -diff .` and it is showing differences.  Mainly with string interpolation changes:  `$var` to `${var}`.

Are you on the latest V?

**Comment by stonesword0** [comment]
I'm on the one from the AUR. Let me try installing from source and running fmt

**Comment by stonesword0** [comment]
Done 👍

**Comment by stonesword0** [comment]
All good to merge 👍

**Pull request merged**
