### PR TITLE
Replace hard-coded spaces with flag.space const

### PR DESCRIPTION
**Pull request by mike-ward**
Replaces hard-coded spaces with the const for options gap from the flag module.

### CODE REVIEW

**Comment by JalonSolov** [comment]
Hmm... the idea is good for the future, but for now, this imports the ENTIRE flag module, just to use that single feature.  Is it worth it, for that?

**Comment by mike-ward** [comment]
Not sure why that's an issue here. Your call.

**Comment by JalonSolov** [comment]
What do you think, @spytheman ?

**Comment by JalonSolov** [comment]
Eh.  We can always change it later.  Better to merge this one than leave it hanging.

**Pull request merged**
