### PR TITLE
fix: make wc conform to original behavior

### PR DESCRIPTION
**Pull request by igrekus**
WC was not replicating the original behavior, this PR fixes various stuff:

- add support for `--files0-from` option
- fix `--max-line-length` not working correctly on files with no trailing newline 
- fix `--max-line-length` not being able to handle lines over 16k chars long
- fix tab char count behavior
- fix stdin stream formatting
- fix total line formatting
- restore original repeated file behavior
- update annotation syntax to the most recent V standard
- update const definition syntax to the most recent V standard
- add tests for all updates

### CODE REVIEW

**Comment by igrekus** [comment]
I had to ditch the parallel computation because it interfered with `--max-line-length` option implementation.

**Comment by verulian** [comment]
do you think crazy if parallel computation worked when no `--max-line-length` is used since it is probably used far less frequently with?

**Comment by igrekus** [comment]
As I confirmed in the discord channel, the main goal for now is 1-to-1 100% compliant implementation of the original behavior.

I think we can simply make two branches, parallel for runs with no --max-line-length and sync for runs with it enabled, but since it is not an immediate goal, I didn't pollute the code with two implementations.

Anyway, I'm willing to adapt.

**Comment by JalonSolov** [comment]
A _lot_ of the `coreutils` files needed to be reformatted, and I've taken care of that, but you'll need to merge with latest and take care of the conflicts before this can be pushed.

**Comment by igrekus** [comment]
Yes, they did, but I thought it'd be better to open an unrelated PR.

**Pull request merged**
